# -*- Makefile -*-

announce:
	@ echo "Source configuration ..."

cparserlib:
	@ echo "CIL parser compilation ..."
	$(MAKE) -C cparser all install
	echo "let parser_lib = \"`pwd`/lib\"" > myocamlbuild_config.ml

configure: announce cparserlib

