
(** [simplify p] removes in the Clight program [p] references to external
    functions generated by the Lustre compiler and that we do not know of. *)

val simplify : Clight.program -> Clight.program
